package Rechoarder::Model::RechoarderDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Rechoarder::Schema',

    connect_info => {
        dsn => 'dbi:Pg:dbname=demo_app_db;host=127.0.0.1;port=5432',
        user => 'demo_app_user',
        password => 'my_demo_password',
    }
);

=head1 NAME

Rechoarder::Model::RechoarderDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Rechoarder>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Rechoarder::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Louis Erickson

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
